# Generated by Django 5.0.1 on 2026-04-12 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre interno de la plantilla', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('recordatorio', 'Recordatorio'), ('publicidad', 'Publicidad'), ('otro', 'Otro')], default='recordatorio', max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo_html', models.TextField(help_text='Cuerpo en HTML. Variables disponibles: {{nombre}}, {{vehiculo}}, {{medida}}, {{fecha}}')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Correo',
                'verbose_name_plural': 'Plantillas de Correo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del recordatorio', max_length=100)),
                ('frecuencia', models.CharField(choices=[('unico', 'Envío único'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral (cada 2 meses)'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20)),
                ('proxima_ejecucion', models.DateTimeField(help_text='Fecha y hora del próximo envío')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recordatorios', to='notificaciones.plantillacorreo')),
            ],
            options={
                'verbose_name': 'Recordatorio Automático',
                'verbose_name_plural': 'Recordatorios Automáticos',
                'ordering': ['proxima_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='EnvioCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario_email', models.EmailField(max_length=254)),
                ('destinatario_nombre', models.CharField(max_length=200)),
                ('asunto', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido')], default='enviado', max_length=20)),
                ('error_detalle', models.TextField(blank=True)),
                ('enviado_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_enviados', to='clientes.cliente')),
                ('recordatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='notificaciones.recordatorio')),
            ],
            options={
                'verbose_name': 'Envío de Correo',
                'verbose_name_plural': 'Historial de Envíos',
                'ordering': ['-enviado_at'],
            },
        ),
    ]
