# Generated by Django 5.0.1 on 2026-02-05 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('notas_apertura', models.TextField(blank=True)),
                ('notas_cierre', models.TextField(blank=True)),
                ('empleado_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_abiertas', to='nomina.empleado')),
                ('empleado_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_cerradas', to='nomina.empleado')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('billetes_1000', models.IntegerField(default=0, verbose_name='Billetes de $1,000')),
                ('billetes_500', models.IntegerField(default=0, verbose_name='Billetes de $500')),
                ('billetes_200', models.IntegerField(default=0, verbose_name='Billetes de $200')),
                ('billetes_100', models.IntegerField(default=0, verbose_name='Billetes de $100')),
                ('billetes_50', models.IntegerField(default=0, verbose_name='Billetes de $50')),
                ('billetes_20', models.IntegerField(default=0, verbose_name='Billetes de $20')),
                ('monedas_20', models.IntegerField(default=0, verbose_name='Monedas de $20')),
                ('monedas_10', models.IntegerField(default=0, verbose_name='Monedas de $10')),
                ('monedas_5', models.IntegerField(default=0, verbose_name='Monedas de $5')),
                ('monedas_2', models.IntegerField(default=0, verbose_name='Monedas de $2')),
                ('monedas_1', models.IntegerField(default=0, verbose_name='Monedas de $1')),
                ('monedas_050', models.IntegerField(default=0, verbose_name='Monedas de $0.50')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.empleado')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arqueos', to='caja.caja')),
            ],
            options={
                'verbose_name': 'Arqueo de Caja',
                'verbose_name_plural': 'Arqueos de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(blank=True, help_text='Ejemplo: Servicios, Gastos operativos, etc.', max_length=100)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='caja.caja')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.empleado')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
