# Generated by Django 5.0.1 on 2026-05-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_num_operacion_num_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cfdi_uuid',
            field=models.CharField(blank=True, help_text='UUID del CFDI emitido', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='factura_pendiente',
            field=models.BooleanField(default=False, help_text='Cliente solicitó factura'),
        ),
        migrations.AddField(
            model_name='venta',
            name='facturada',
            field=models.BooleanField(default=False),
        ),
    ]
