# Generated by Django 5.0.1 on 2026-05-05 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_nomina_empleado_extended'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('cerrada', 'Cerrada'), ('pagada', 'Pagada')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_general', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_comisiones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_domingos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Período de Nómina',
                'verbose_name_plural': 'Períodos de Nómina',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión (ej. 10 = 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='empleado',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='pago_dominical',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo por domingo trabajado', max_digits=10),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salario base semanal en MXN', max_digits=10),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_pago',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='semanal', max_length=20, verbose_name='Periodicidad de pago'),
        ),
        migrations.CreateModel(
            name='LineaNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('domingo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_percepciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_nomina', to='nomina.empleado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='nomina.periodonomina')),
            ],
            options={
                'verbose_name': 'Línea de Nómina',
                'verbose_name_plural': 'Líneas de Nómina',
                'ordering': ['empleado__apellido', 'empleado__nombre'],
                'unique_together': {('periodo', 'empleado')},
            },
        ),
        migrations.DeleteModel(
            name='Nomina',
        ),
    ]
