# Generated by Django 5.0.1 on 2026-02-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, help_text='Precio unitario de compra', max_digits=10)),
                ('fecha_compra', models.DateField()),
                ('numero_factura', models.CharField(max_length=50)),
                ('en_inventario', models.BooleanField(default=True, help_text='Si las llantas están en inventario')),
                ('factura_consumida', models.BooleanField(default=False, help_text='Si la factura fue completamente vendida')),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrada de Inventario',
                'verbose_name_plural': 'Entradas de Inventario',
                'ordering': ['-fecha_compra', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marcas/')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del producto', max_length=50, unique=True)),
                ('medida', models.CharField(help_text='Ej: 225/65R17', max_length=20)),
                ('modelo', models.CharField(help_text='Ej: Scorpion ATR', max_length=100)),
                ('indice_carga', models.IntegerField(help_text='Ej: 82, 84, 87')),
                ('indice_velocidad', models.CharField(choices=[('T', 'T - hasta 190 km/h'), ('H', 'H - hasta 210 km/h'), ('V', 'V - hasta 240 km/h'), ('W', 'W - hasta 270 km/h'), ('Y', 'Y - hasta 300 km/h'), ('Z', 'Z - más de 240 km/h')], max_length=2)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_minimo', models.IntegerField(default=2, help_text='Alerta cuando stock sea menor a este valor')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['medida', 'marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('dias_credito', models.IntegerField(default=0, help_text='Días de crédito otorgados')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SalidaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio unitario de venta', max_digits=10)),
                ('precio_costo', models.DecimalField(decimal_places=2, help_text='Precio unitario de costo', max_digits=10)),
                ('utilidad', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha_venta', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salida de Inventario',
                'verbose_name_plural': 'Salidas de Inventario',
                'ordering': ['-fecha_venta', '-created_at'],
            },
        ),
    ]
