# Generated by Django 5.0.1 on 2026-05-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_pagoproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradainventario',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_lista', 'En lista'), ('sin_existencia', 'Sin existencia'), ('consumido', 'Consumido/Vendido')], default='disponible', help_text='Estado del lote en inventario', max_length=20),
        ),
    ]
