# Generated by Django 5.0.1 on 2026-05-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_add_missing_fk_columns'),
        ('inventario', '0004_entradainventario_estado'),
    ]

    operations = [
    ]
